import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.comunicacion.*
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificadorBotzza.objetivos.*;

import icaro.aplicaciones.agentes.AgenteAplicacionIdentificadorBotzza.tareas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificadorBotzza.tools.*;
import icaro.aplicaciones.informacion.gestionPizzeria.*;
import icaro.aplicaciones.agentes.AgenteAplicacionPizzero.objetivos.*;
import icaro.infraestructura.entidadesBasicas.interfaces.InterfazUsoAgente;
import icaro.infraestructura.entidadesBasicas.NombresPredefinidos;
import icaro.infraestructura.entidadesBasicas.comunicacion.MensajeSimple;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;


// "grupo" es el nombre del usuario del chat.

rule "Creacion de los objetivos iniciales"
when 
then 
	TareaSincrona tarea = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
    tarea.ejecutar();
	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end

/*
rule "Saludo Inicial"
when
then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SaludoInicial.class);
     tarea.ejecutar(VocabularioGestionPizzeria.IdentRecursoComunicacionChat);
     recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
*/

rule "Saludo inicial cuando el grupo dice algo que no es un saludo"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo)
    not( exists (Usuario(username == identInterlc )))
 then
 	Usuario gr = new Usuario();
 	gr.username = identInterlc;
 	insert( gr );
 	FocoUsuario fgr = new FocoUsuario(identInterlc);
 	Objetivo ob = new ObtenerInfoUsuario();
 	ob.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( ob );
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(identInterlc,ConversacionBotzza.msg("saludoInicialNoSaludo"));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end

rule "Saludo inicial cuando el grupo saluda y no se conoce"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
    not( exists (Usuario(username == identInterlc )))
 then
 	Usuario gr = new Usuario();
 	gr.username = identInterlc;
 	insert( gr );
 	FocoUsuario fgr = new FocoUsuario(identInterlc);
 	Objetivo ob = new ObtenerInfoUsuario();
 	ob.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( ob );
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(identInterlc,ConversacionBotzza.msg("saludoInicialDesconocido"));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end

rule "Saludo inicial cuando el grupo saluda y se conoce"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
   	gr:Usuario(username == identInterlc)
 then
 	FocoUsuario fgr = new FocoUsuario(identInterlc);
 	Objetivo ob = new ObtenerInfoUsuario();
 	ob.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( ob );
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(identInterlc,ConversacionBotzza.msg("saludoInicial"));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end


rule "Respuesta ante resaludo del grupo conocido"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
   	gr:Usuario(username == identInterlc)
 then
  	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
     tarea.ejecutar(identInterlc,ConversacionBotzza.msg("volverASaludar"));
     recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
     gr.actividad();
     retract(notif);
end


rule "Notificar desconocimiento"
 when
 	notif:Notificacion(group:identNotificador, tipoNotificacion == VocabularioGestionPizzeria.ExtraccionSemanticaNull )
	gr:Usuario(username == group)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
     tarea.ejecutar(group,ConversacionBotzza.msg("desconocido"));
     recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
     gr.actividad();
     retract(notif);
end

rule "Despedirse"
	when 
	 notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.despedida)
 	 gr:Usuario(username == identInterlc )
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	// TODO eliminar sesion ?
   TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
     tarea.ejecutar(gr.username,  ConversacionBotzza.msg("despedida"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   
   retract( notif );
end

////////////////////////////

rule "Regla de solicitar nombre"
 when
 	obj:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoUsuario(username == group, foco == null)
   	not (exists (ObtenerNombreUsuario(objectReferenceId == group)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo ob = new ObtenerNombreUsuario();
  	ob.setobjectReferenceId(group);
  	fc.setFoco(ob);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(group,ConversacionBotzza.msg("solicitarNombre"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	insert(ob);
end

rule "Regla de solicitar nombre cuando se obtiene algo que no es el nombre"
 when
 	obGeneral:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerNombreUsuario(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoUsuario(username == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion != tipoNotif.nombres, msgg:mensajeNotificacion )
    gr:Usuario(username == group)
 then
 	
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(group,ConversacionBotzza.msg("solicitarNombreImperativo"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   
   	retract(notif);
end

rule "Regla de obtencion del nombre" 
 when
 	obGeneral:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerNombreUsuario(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoUsuario(username == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.nombres, msgg:mensajeNotificacion )
    gr:Usuario(username == group)
 then
 	ob.setSolved();
 	
 	gr.setNombre(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(group,ConversacionBotzza.msg("tengoTuNombre"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	// creamos objetivo de obtener el apellido, ya que tenemos el nombre!
   	Objetivo ob2 = new ObtenerApellidoUsuario();
  	ob2.setobjectReferenceId(group);
  	//fc.setFoco(ob2);
   	
   	
   	update(ob);
   	update(fc);
   	retract(notif);
   	insert(ob2);
end


rule "Regla de solicitar apellido"
 when
 	obj:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.PENDING)
 	
 	obj2:ObtenerApellidoUsuario(objectReferenceId == group, state == Objetivo.PENDING)
 	fc:FocoUsuario(username == group, foco == null)
    gr:Usuario(username == group)
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	fc.setFoco(obj2);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(group,ConversacionBotzza.msg("solicitarApellido"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	update(obj2);
end

rule "Regla de solicitar el apellido cuando se obtiene algo que no es el apellido" 
 when
 	obGeneral:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerApellidoUsuario(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoUsuario(username == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion != tipoNotif.apellidos, msgg:mensajeNotificacion )
    gr:Usuario(username == group)
 then
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(group,ConversacionBotzza.msg("solicitarApellidoImperativo"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	retract(notif);
end


rule "Regla de obtencion del apellido" 
 when
 	obGeneral:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.PENDING)
 	ob:ObtenerApellidoUsuario(state == Objetivo.PENDING, objectReferenceId == group)
 	fc:FocoUsuario(username == group, foco == ob )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.apellidos, msgg:mensajeNotificacion )
    gr:Usuario(username == group)
 then
 	ob.setSolved();
 	
 	gr.setApellidos(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenericoBotzza.class);
    tarea.ejecutar(group,ConversacionBotzza.msg("tengoTuApellido"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	// creamos objetivo de obtener la masa de pizza, ya que tenemos el apellido!
   	//Objetivo ob2 = new SolicitarNombrePizza();
  	//ob2.setobjectReferenceId(group);
  	//fc.setFoco(ob2);
  	
   	obGeneral.setSolved(); // FIXME esto hay que cambiarlo de sitio cuando haya más cosas que el apellido
   	update(obGeneral);
   	
   	
   	fc.setFoco(null);
   	update(ob);
   	update(fc);
   	retract(notif);
   //	insert(ob2);
end

rule "Enviar mensaje al agente contexto cuando acaba el agente identificador"
when
 	obGeneral:ObtenerInfoUsuario(group:objectReferenceId, state == Objetivo.SOLVED)
then
	InterfazUsoAgente iftAgente = (InterfazUsoAgente)NombresPredefinidos.
  		REPOSITORIO_INTERFACES_OBJ.obtenerInterfaz(NombresPredefinidos.ITF_USO + VocabularioGestionPizzeria.IdentAgenteContexto);
  	Notificacion notifPide = new Notificacion(agentId);
  	notifPide.setTipoNotificacion(tipoNotif.pidePizza);
  	notifPide.setMensajeNotificacion("El agente identificador ha terminado ");
   	MensajeSimple mensaje = new MensajeSimple(notifPide, VocabularioGestionPizzeria.IdentAgenteIdentificadorBotzza, VocabularioGestionPizzeria.IdentAgenteContexto);
   	System.out.println(mensaje);
   	iftAgente.aceptaMensaje(mensaje);
end


